"""
Language Detector
Offline language detection via lingua. Detects the user's language from input
text and injects a structured language rule into the HookResult.
"""

from __future__ import annotations

try:
    from lingua import Language, LanguageDetectorBuilder  # type: ignore[import-untyped]
    _LINGUA_AVAILABLE = True
except ImportError:
    _LINGUA_AVAILABLE = False

from hooks.hook_contract import HookContext, HookResult

# Policy configuration

CONFIDENCE_THRESHOLD: float = 0.75

LANGUAGE_RULES: dict[str, str] = {
    "Spanish": (
        "All user-facing artifacts generated by the workflow SHALL be written "
        "in Spanish. Internal reasoning, intermediate processing, and backend "
        "prompts may remain in English. Do not mix Spanish and English in "
        "final deliverables unless the original requirement explicitly contains "
        "bilingual content."
    ),
    "English": (
        "All user-facing artifacts generated by the workflow SHALL be written "
        "in English."
    ),
    "Portuguese": (
        "All user-facing artifacts generated by the workflow SHALL be written "
        "in Portuguese. Internal reasoning and backend prompts may remain in "
        "English. Do not mix languages in final deliverables."
    ),
    "French": (
        "All user-facing artifacts generated by the workflow SHALL be written "
        "in French. Internal reasoning and backend prompts may remain in "
        "English. Do not mix languages in final deliverables."
    ),
    "German": (
        "All user-facing artifacts generated by the workflow SHALL be written "
        "in German. Internal reasoning and backend prompts may remain in "
        "English. Do not mix languages in final deliverables."
    ),
    "Italian": (
        "All user-facing artifacts generated by the workflow SHALL be written "
        "in Italian. Internal reasoning and backend prompts may remain in "
        "English. Do not mix languages in final deliverables."
    ),
}

_LINGUA_LANGUAGE_MAP: dict[str, str] = {
    "SPANISH": "Spanish",
    "ENGLISH": "English",
    "PORTUGUESE": "Portuguese",
    "FRENCH": "French",
    "GERMAN": "German",
    "ITALIAN": "Italian",
}


# Detection

def _detect_language(text: str) -> tuple[str, float]:
    """
    Detect the language of the input text using lingua (offline).

    Returns:
        (language_name, confidence) — e.g. ("Spanish", 0.98)
        Falls back to ("English", raw_confidence) if:
          - lingua is not installed
          - detected language is not in the supported set
          - confidence is below CONFIDENCE_THRESHOLD (0.75)
    """
    if not _LINGUA_AVAILABLE or not text or not text.strip():
        return ("English", 0.0)

    try:
        target_languages = [
            Language.ENGLISH,
            Language.SPANISH,
            Language.PORTUGUESE,
            Language.FRENCH,
            Language.GERMAN,
            Language.ITALIAN,
        ]
        detector = (
            LanguageDetectorBuilder
            .from_languages(*target_languages)
            .with_minimum_relative_distance(0.1)
            .build()
        )
        result = detector.detect_language_of(text)

        if result is None:
            return ("English", 0.0)

        lang_name = _LINGUA_LANGUAGE_MAP.get(result.name, None)
        if lang_name is None:
            return ("English", 0.0)

        confidence_values = detector.compute_language_confidence_values(text)
        confidence = 0.0
        for cv in confidence_values:
            if cv.language == result:
                confidence = round(cv.value, 4)
                break

        if confidence < CONFIDENCE_THRESHOLD:
            return ("English", confidence)

        return (lang_name, confidence)

    except Exception:  # noqa: BLE001 — lingua failures must never crash the hook runtime
        return ("English", 0.0)


def build_language_result(context: HookContext, trace_id: str) -> HookResult:
    """
    Run language detection and build an allow HookResult with enriched context.
    """
    detected_lang, confidence = _detect_language(context.user_prompt)
    rule = LANGUAGE_RULES.get(detected_lang, LANGUAGE_RULES["English"])

    sanitized = {
        "user_prompt": context.user_prompt,
        "input_files": context.input_files,
    }

    return HookResult(
        execute_workflow=True,
        trace_id=trace_id,
        language=detected_lang,
        confidence=confidence,
        language_rule=rule,
        sanitized_context=sanitized,
    )
