#!/usr/bin/env python3
"""
PreToolUse Hook Implementation

Deterministic validation layer that executes BEFORE any tool is used by the
orchestrator agent. This moves critical governance out of the LLM's
probabilistic reasoning and into auditable, predictable Python code.

Responsibilities:
    1. Security Gate  — Block executable / risky file extensions and MIME types
                        using a default-deny policy (fail-closed).
    2. Language Detector — Detect the user's language offline via lingua
                           and inject a structured language rule.
    3. Emit HookResult — Print structured JSON to stdout for the orchestrator.
"""

from __future__ import annotations

import json
import re
import sys
import uuid
from pathlib import Path

# ---------------------------------------------------------------------------
# Optional imports — graceful degradation if libraries are not installed.
# Run: pip install -r requirements-hooks.txt
# ---------------------------------------------------------------------------

try:
    import magic  # type: ignore[import-untyped]  # python-magic: optional, graceful degradation
    _MAGIC_AVAILABLE = True
except ImportError:
    _MAGIC_AVAILABLE = False

try:
    from lingua import (  # type: ignore[import-untyped]  # optional
        Language,
        LanguageDetectorBuilder,
    )
    _LINGUA_AVAILABLE = True
except ImportError:
    _LINGUA_AVAILABLE = False

# Local contract, always available, zero external deps
from hooks.hook_contract import HookContext, HookExtensions, HookResult

# ---------------------------------------------------------------------------
# Security constants
# Policy decision: default-deny. Unknown extensions are BLOCKED, not allowed.
# Override: pass allowed_extensions via HookContext.extensions at runtime.
# See README.md §Hook Layer for the rationale behind each category.
# ---------------------------------------------------------------------------

BLOCKED_EXTENSIONS: frozenset[str] = frozenset({
    # Executables & system binaries
    ".exe", ".dll", ".so", ".bat", ".cmd", ".ps1", ".sh",
    # Scripts (including .py — blocked by default; override via extensions)
    ".js", ".vbs", ".py",
    # Binary / packaged
    ".bin", ".apk", ".jar",
    # Office macros
    ".docm", ".xlsm",
})

# Blocked MIME type prefixes / exact values
BLOCKED_MIME_PREFIXES: tuple[str, ...] = (
    "application/x-executable",
    "application/x-sharedlib",
    "application/x-dosexec",
    "application/x-msdownload",
    "application/x-sh",
    "application/x-python",
    "application/java-archive",
    "application/vnd.ms-office",
    "application/zip",          # Catch archive recursion attempts
    "application/x-zip",
)

# File size limit — default 10 MB.
# Decision rationale: resource consumption optimization. Oversized files
# Override: see docs/architecture_implementation_details_roadmap.md Hook Layer for instructions on changing this value.
MAX_FILE_SIZE_MB: int = 10
MAX_FILE_SIZE_BYTES: int = MAX_FILE_SIZE_MB * 1024 * 1024

# ---------------------------------------------------------------------------
# Language detection constants
# Confidence threshold: 0.75.
# Below this value the hook falls back to English and logs the raw score.
# ---------------------------------------------------------------------------

CONFIDENCE_THRESHOLD: float = 0.75

LANGUAGE_RULES: dict[str, str] = {
    "Spanish": (
        "All user-facing artifacts generated by the workflow SHALL be written "
        "in Spanish. Internal reasoning, intermediate processing, and backend "
        "prompts may remain in English. Do not mix Spanish and English in "
        "final deliverables unless the original requirement explicitly contains "
        "bilingual content."
    ),
    "English": (
        "All user-facing artifacts generated by the workflow SHALL be written "
        "in English."
    ),
    "Portuguese": (
        "All user-facing artifacts generated by the workflow SHALL be written "
        "in Portuguese. Internal reasoning and backend prompts may remain in "
        "English. Do not mix languages in final deliverables."
    ),
    "French": (
        "All user-facing artifacts generated by the workflow SHALL be written "
        "in French. Internal reasoning and backend prompts may remain in "
        "English. Do not mix languages in final deliverables."
    ),
    "German": (
        "All user-facing artifacts generated by the workflow SHALL be written "
        "in German. Internal reasoning and backend prompts may remain in "
        "English. Do not mix languages in final deliverables."
    ),
    "Italian": (
        "All user-facing artifacts generated by the workflow SHALL be written "
        "in Italian. Internal reasoning and backend prompts may remain in "
        "English. Do not mix languages in final deliverables."
    ),
}

# Lingua language objects mapped to display names used in LANGUAGE_RULES
_LINGUA_LANGUAGE_MAP: dict[str, str] = {
    "SPANISH": "Spanish",
    "ENGLISH": "English",
    "PORTUGUESE": "Portuguese",
    "FRENCH": "French",
    "GERMAN": "German",
    "ITALIAN": "Italian",
}


# ===========================================================================
# Security Gate
# ===========================================================================

def _resolve_file_paths(tool_input: dict) -> list[str]:
    """
    Extract file paths referenced in the tool's input arguments.

    Scans all string values in the tool_input dict for path-like strings
    (values starting with '/' or './' or containing a file extension).
    """
    paths: list[str] = []
    for value in tool_input.values():
        if isinstance(value, str):
            candidate = value.strip()
            # Heuristic: treat as a file path if it starts with known prefixes
            # or contains a dot suffix suggesting a file extension.
            if (
                candidate.startswith(("/", "./", "../")) or len(candidate) < 512 and "." in Path(candidate).name
            ):
                paths.append(candidate)
        elif isinstance(value, list):
            for item in value:
                if isinstance(item, str):
                    paths.append(item.strip())
    return paths


def _effective_blocked_extensions(extensions: HookExtensions | None) -> frozenset[str]:
    """Return the active deny-list, minus any caller-granted overrides."""
    if extensions and extensions.allowed_extensions:
        overrides = frozenset(ext.lower() for ext in extensions.allowed_extensions)
        return BLOCKED_EXTENSIONS - overrides
    return BLOCKED_EXTENSIONS


def _check_extension(filepath: str, blocked: frozenset[str]) -> str | None:
    """
    Return a block reason if ANY suffix in the file path is blocked.
    Uses pathlib.Path.suffixes to catch compound extensions like .pdf.exe.
    """
    suffixes = [s.lower() for s in Path(filepath).suffixes]
    for suffix in suffixes:
        if suffix in blocked:
            return (
                f"Blocked file extension detected: '{suffix}' in '{Path(filepath).name}'. "
                f"Executable and script files are not permitted as input."
            )
    return None


def _check_mime_type(filepath: str) -> str | None:
    """
    Return a block reason if the MIME type of the file is on the deny-list.
    Falls back gracefully if python-magic is not installed.
    """
    if not _MAGIC_AVAILABLE:
        return None  # Skip MIME check; rely on extension check only

    try:
        p = Path(filepath)
        if not p.exists() or not p.is_file():
            return None  # File does not exist yet — skip MIME check
        mime = magic.from_file(str(p), mime=True)
        if mime and any(mime.startswith(prefix) for prefix in BLOCKED_MIME_PREFIXES):
            return (
                f"Blocked MIME type detected: '{mime}' for file '{p.name}'. "
                f"This file type is not permitted as input."
            )
    except (OSError, ValueError) as e:
        # Log and gracefully degrade to extension check only
        print(f"[WARNING] MIME detection failed: {e}", file=sys.stderr)
    return None


def _check_file_size(filepath: str, max_bytes: int) -> str | None:
    """Return a block reason if the file exceeds the size limit."""
    try:
        p = Path(filepath)
        if p.exists() and p.is_file():
            size = p.stat().st_size
            if size > max_bytes:
                size_mb = size / (1024 * 1024)
                limit_mb = max_bytes / (1024 * 1024)
                return (
                    f"File '{p.name}' exceeds the maximum allowed size "
                    f"({size_mb:.1f} MB > {limit_mb:.0f} MB limit). "
                    f"Reduce file size or split into smaller inputs."
                )
    except (OSError, ValueError) as e:
        # Log and gracefully degrade
        print(f"[WARNING] File size check failed: {e}", file=sys.stderr)
    return None

def _check_prompt_injection(prompt: str) -> tuple[str | None, dict | None]:
    """
    Validates the prompt against the strict IEEE format regex.
    Returns (block_reason, extracted_components_dict).
    """
    if not prompt or not prompt.strip():
        return "Prompt is empty or missing. A valid IEEE requirement is required.", None

    # Option executed: Structural Boundary Regex (Universally supports all languages)
    pattern = re.compile(
        r"^(?:Run\s+)?(RF-[a-zA-Z0-9\-]+):\s*(.*?)\.?\s*(?:US\[|User Story:\s*)(.*?)(?:\])?\.?$",
        re.IGNORECASE | re.DOTALL
    )
    
    match = pattern.match(prompt.strip())
    if not match:
        return (
            ("Prompt Injection Protection: Input does not strictly adhere to the expected IEEE format or contains extraneous content. "
            "Format required: Run RF-[ID]: [action]. US[[user story]] OR User Story: [user story]."),
            None
        )
        
    extracted = {
        "rf_id": match.group(1).strip(),
        "action": match.group(2).strip(),
        "user_story": match.group(3).strip(),
    }
    
    # Reconstruct sanitized prompt to strip out any hidden text outside the capture groups
    sanitized_prompt = (
        f"{extracted['rf_id']}: {extracted['action']}. "
        f"US[{extracted['user_story']}]."
    )
    extracted["sanitized_prompt"] = sanitized_prompt
    
    return None, extracted


def run_security_gate(context: HookContext) -> HookResult | None:
    """
    Execute the security validation sequence (fail-closed).

    Returns a blocking HookResult if any check fails, or None if all pass.
    Sequence:
        1. Extension check (all suffixes, catches compound extensions)
        2. MIME type check  (requires python-magic + libmagic)
        3. File size check  (10 MB default)
    """
    trace_id = _generate_trace_id()
    blocked_ext = _effective_blocked_extensions(
        context.extensions if context.extensions else None
    )
    max_bytes = MAX_FILE_SIZE_BYTES
    if context.runtime_config:
        limit_mb = context.runtime_config.get("max_file_size_mb", MAX_FILE_SIZE_MB)
        max_bytes = int(limit_mb) * 1024 * 1024

    for filepath in context.input_files:
        reason = _check_extension(filepath, blocked_ext)
        if reason:
            return HookResult(
                execute_workflow=False,
                trace_id=trace_id,
                risk_level="high",
                block_reason=reason,
            )

        reason = _check_mime_type(filepath)
        if reason:
            return HookResult(
                execute_workflow=False,
                trace_id=trace_id,
                risk_level="high",
                block_reason=reason,
            )

        reason = _check_file_size(filepath, max_bytes)
        if reason:
            return HookResult(
                execute_workflow=False,
                trace_id=trace_id,
                risk_level="medium",
                block_reason=reason,
            )

    return None  # All checks passed


# ===========================================================================
# Language Detection
# ===========================================================================

def _detect_language(text: str) -> tuple[str, float]:
    """
    Detect the language of the input text using lingua (offline).

    Returns:
        (language_name, confidence) — e.g. ("Spanish", 0.98)
        Falls back to ("English", raw_confidence) if:
          - lingua is not installed
          - detected language is not in the supported set
          - confidence is below CONFIDENCE_THRESHOLD (0.75)
    """
    if not _LINGUA_AVAILABLE or not text or not text.strip():
        return ("English", 0.0)

    try:
        target_languages = [
            Language.ENGLISH,
            Language.SPANISH,
            Language.PORTUGUESE,
            Language.FRENCH,
            Language.GERMAN,
            Language.ITALIAN,
        ]
        detector = (
            LanguageDetectorBuilder
            .from_languages(*target_languages)
            .with_minimum_relative_distance(0.1)
            .build()
        )
        result = detector.detect_language_of(text)

        if result is None:
            return ("English", 0.0)

        lang_name = _LINGUA_LANGUAGE_MAP.get(result.name, None)
        if lang_name is None:
            return ("English", 0.0)

        # Get confidence score
        confidence_values = detector.compute_language_confidence_values(text)
        confidence = 0.0
        for cv in confidence_values:
            if cv.language == result:
                confidence = round(cv.value, 4)
                break

        if confidence < CONFIDENCE_THRESHOLD:
            # Fallback to English — keep raw score for diagnostics
            return ("English", confidence)

        return (lang_name, confidence)

    except (RuntimeError, LookupError) as e:
        # Log detection failure and fall back to English
        print(f"[WARNING] Language detection failed: {e}", file=sys.stderr)
        return ("English", 0.0)


def build_language_result(
    context: HookContext,
    trace_id: str,
) -> HookResult:
    """
    Run language detection and build an allow HookResult with enriched context.
    """
    detected_lang, confidence = _detect_language(context.user_prompt)
    rule = LANGUAGE_RULES.get(detected_lang, LANGUAGE_RULES["English"])

    sanitized = {
        "user_prompt": context.user_prompt,
        "input_files": context.input_files,
    }

    return HookResult(
        execute_workflow=True,
        trace_id=trace_id,
        language=detected_lang,
        confidence=confidence,
        language_rule=rule,
        sanitized_context=sanitized,
    )


# ===========================================================================
# Utility
# ===========================================================================

def _generate_trace_id() -> str:
    """Generate a UUID4 trace ID for audit trail linkage."""
    return str(uuid.uuid4())


def _parse_stdin() -> tuple[dict, list[str]]:
    """
    Read and parse the JSON payload from stdin (Claude PreToolUse protocol).

    The runtime passes a JSON object with at minimum:
        { "tool_name": "...", "tool_input": { ... } }

    Returns:
        (raw_payload, list_of_file_paths)
    """
    try:
        raw = sys.stdin.read()
        if not raw.strip():
            return ({}, [])
        payload = json.loads(raw)
        tool_input = payload.get("tool_input", {})
        file_paths = _resolve_file_paths(tool_input)
        return (payload, file_paths)
    except json.JSONDecodeError:
        return ({}, [])


def _extract_user_prompt(payload: dict) -> str:
    """
    Extract the user-facing text for language detection.

    Prefers the 'prompt' or 'query' keys in tool_input; falls back to
    searching for any string value longer than 20 chars.
    """
    tool_input = payload.get("tool_input", {})
    for key in ("prompt", "query", "content", "text", "user_prompt"):
        val = tool_input.get(key, "")
        if isinstance(val, str) and len(val.strip()) > 10:
            return val.strip()

    # Fallback: use the longest string value in tool_input
    candidates = [
        v for v in tool_input.values()
        if isinstance(v, str) and len(v.strip()) > 20
    ]
    if candidates:
        return max(candidates, key=len)

    return ""


# ===========================================================================
# Main entrypoint
# ===========================================================================

def main() -> None:
    """
    PreToolUse hook entrypoint.

    Reads tool input from stdin, runs security gate and language detection,
    and emits a HookResult as JSON to stdout.

    Exit code is always 0 — a non-zero exit would crash the agent runtime.
    """
    payload, input_files = _parse_stdin()
    user_prompt = _extract_user_prompt(payload)

    context = HookContext(
        user_prompt=user_prompt,
        input_files=input_files,
    )

    trace_id = _generate_trace_id()

    # --- Phase 1: Security Gate (fail-closed) ---
    block_result = run_security_gate(context)
    if block_result is not None:
        # Ensure the same trace_id is used for consistent audit linkage
        block_result.trace_id = trace_id
        print(json.dumps(block_result.to_dict(), ensure_ascii=False))
        sys.exit(0)

    # --- Phase 1.5: Prompt Injection Gate (fail-closed) ---
    prompt_reason, extracted = _check_prompt_injection(user_prompt)
    if prompt_reason:
        prompt_block = HookResult(
            execute_workflow=False,
            trace_id=trace_id,
            risk_level="high",
            block_reason=prompt_reason,
        )
        print(json.dumps(prompt_block.to_dict(), ensure_ascii=False))
        sys.exit(0)

    # Inject sanitized prompt back into context for language detection
    if extracted and "sanitized_prompt" in extracted:
        context.user_prompt = extracted["sanitized_prompt"]

    # --- Phase 2: Language Detection (enrichment) ---
    allow_result = build_language_result(context, trace_id)
    print(json.dumps(allow_result.to_dict(), ensure_ascii=False))
    sys.exit(0)


if __name__ == "__main__":
    main()